package namba.wallet.nambaone.common.analytics

object Events {
    const val AUTH_USER_ONBOARDING_SUCCEEDED = "user_onboarding_succeeded"
    const val AUTH_PHONE_NUMBER_SUCCEEDED = "phone_number_succeeded"
    const val AUTH_PHONE_NUMBER_FAILED = "phone_number_failed"
    const val AUTH_TERMS_OPENED = "terms_opened"
    const val AUTH_TERMS_ACCEPTED = "terms_accepted"
    const val AUTH_SMS_CODE_RESENT = "sms_code_resent"
    const val AUTH_SMS_CODE_RIGHT_ENTERED = "sms_code_right_entered"
    const val AUTH_SMS_CODE_FAILED = "sms_code_failed"
    const val AUTH_DEVICES_LIST_OPENED = "devices_list_opened"
    const val AUTH_DEVICE_DELETED = "device_deleted"
    const val AUTH_SET_PIN_CODE_STARTED = "set_pin_code_started"
    const val AUTH_SET_PIN_CODE_SUCCEEDED = "set_pin_code_succeeded"
    const val AUTH_SET_PIN_CODE_FAILED = "set_pin_code_failed"
    const val AUTH_SET_DATA_SUCCEEDED = "set_data_succeeded"
    const val AUTH_PIN_CODE_SUCCEEDED = "pin_code_succeeded"
    const val AUTH_PIN_CODE_FAILED = "pin_code_failed"
    const val AUTH_SESSION_FINISHED = "session_finished"

    const val PROFILE_OPENED = "profile_opened"
    const val PROFILE_LOGOUT_SUCCEEDED = "profile_logout_succeeded"
    const val PROFILE_EDIT_OPENED = "profile_edit_opened"
    const val PROFILE_EDIT_SUCCEEDED = "profile_edit_succeeded"
    const val PROFILE_EDIT_FAILED = "profile_edit_failed"
    const val PROFILE_LIMITS_SUCCEEDED = "profile_limits_succeeded"
    const val PROFILE_TOUCHID_SWITCHED = "profile_touchid_switched"
    const val PROFILE_HELP_OPENED = "profile_help_opened"
    const val PROFILE_SUPPORT_OPENED = "profile_support_opened"
    const val PROFILE_PANDEMIC_SUPPORT_OPENED = "profile_response_42500_opened"

    const val DID_PROGRESS_STATUS = "DID_progress_status"
    const val DID_STARTED = "DID_started"
    const val DID_SUCCEEDED = "DID_succeeded"
    const val DID_FAILED = "DID_failed"
    const val DID_STATUS_ON_MODERATION = "DID_status_on_moderation"
    const val DID_ADDRESS_OPENED = "DID_address_opened"
    const val DID_ADDRESS_SUCCEEDED = "DID_address_succeeded"
    const val DID_STATUS_CHECKED = "DID_status_checked"

    const val LEGAL_ACCOUNT_LIST_OPENED = "legal_account_list_opened"
    const val LEGAL_ACCOUNT_ADD_SUCCEEDED = "legal_account_add_succeeded"
    const val LEGAL_CODE_SHARE_SUCCEEDED = "legal_code_share_succeeded"

    const val QR_GENERATE = "qr_generate"
    const val QR_GALLERY_STARTED = "qr_gallery_started"
    const val QR_GALLERY_SELECTED = "qr_gallery_selected"
    const val QR_GALLERY_FAILED = "qr_gallery_failed"
    const val QR_SHARE_STARTED = "qr_share_started"
    const val QR_AMOUNT_ENTERED = "qr_amount_entered"
    const val QR_READ = "qr_read"

    const val TRANSFER_OPENED = "transfer_opened"
    const val TRANSFER_SAVED_CARD_LOAD_FAILED = "transfer_saved_card_load_failed"
    const val TRANSFER_USER_STARTED = "transfer_user_started"
    const val TRANSFER_USER_BY_QR_STARTED = "transfer_user_by_qr_started"
    const val TRANSFER_USER_CONTACT_STARTED = "transfer_user_contact_started"
    const val TRANSFER_USER_CONTACT_SELECTED = "transfer_user_contact_selected"
    const val TRANSFER_IDENTIFICATION_SUGGESTED = "transfer_identification_suggested"
    const val TRANSFER_IDENTIFICATION_ACCEPTED = "transfer_identification_accepted"
    const val TRANSFER_USER_ON_DEMAND_CONFIRM_OPENED = "transfer_user_on_demand_confirm_opened"
    const val TRANSFER_USER_CONFIRM_OPENED = "transfer_user_confirm_opened"
    const val TRANSFER_TO_CARD_STARTED = "transfer_to_card_started"
    const val TRANSFER_TO_NEW_CARD_STARTED = "transfer_to_new_card_started"
    const val TRANSFER_TO_NEW_CARD_SCAN_STARTED = "transfer_to_new_card_scan_started"
    const val TRANSFER_TO_NEW_CARD_SCAN_SUCCEEDED = "transfer_to_new_card_scan_succeeded"
    const val TRANSFER_TO_NEW_CARD_SCAN_FAILED = "transfer_to_new_card_scan_failed"
    const val TRANSFER_TO_SAVED_CARD_STARTED = "transfer_to_saved_card_started"
    const val TRANSFER_TO_CARD_CONFIRM_OPENED = "transfer_to_card_confirm_opened"
    const val TRANSFER_SUCCEEDED = "transfer_succeeded"

    const val CASHIN_OPENED = "cashin_opened"
    const val CASHIN_BY_CARD_STARTED = "cashin_by_card_started"
    const val CASHIN_SAVED_CARD_LOAD_FAILED = "cashin_saved_card_load_failed"
    const val CASHIN_BY_SAVED_CARD_STARTED = "cashin_by_saved_card_started"
    const val CASHIN_BY_CARD_CONFIRM_OPENED = "cashin_by_card_confirm_opened"
    const val CASHIN_BY_CARD_SUCCEEDED = "cashin_by_card_succeeded"
    const val CASHIN_BY_NEW_CARD_STARTED = "cashin_by_new_card_started"
    const val CASHIN_BY_NEW_CARD_SCAN_STARTED = "cashin_by_new_card_scan_started"
    const val CASHIN_BY_NEW_CARD_SCAN_SUCCEEDED = "cashin_by_new_card_scan_succeeded"
    const val CASHIN_BY_NEW_CARD_FAILED = "cashin_by_new_card_failed"
    const val CASHIN_3_DS_OPENED = "cashin_3ds_opened"
    const val CASHIN_3_DS_SUCCEEDED = "cashin_3ds_succeeded"
    const val CASHIN_3_DS_FAILED = "cashin_3ds_failed"

    const val RECEIPT_GENERATED = "receipt_generated"
    const val RECEIPT_FAILED = "receipt_failed"
    const val RECEIPT_SHARED = "receipt_shared"

    const val MAIN_HISTORY_SUCCEEDED = "history_succeeded"
    const val MAIN_HISTORY_FAILED = "history_failed"
    const val MAIN_HISTORY_DETAILS_OPENED = "history_details_opened"
    const val MAIN_BALANCE_SUCCEEDED = "balance_succeeded"
    const val MAIN_BALANCE_FAILED = "balance_failed"

    // branch
    const val BRANCH_REQUEST = "branch_request"
}
